server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona todas as rotas para o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para a API GraphQL
    location /graphql {
        proxy_pass http://api:8080/graphql;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
